/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAtletasRouteImport } from './routes/_authenticated/atletas'
import { Route as AuthenticatedCampoRouteImport } from './routes/_authenticated/campo'
import { Route as AuthenticatedEvolucaoRouteImport } from './routes/_authenticated/evolucao'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedVideoRouteImport } from './routes/_authenticated/video'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAtletasRoute = AuthenticatedAtletasRouteImport.update({
  id: '/_authenticated/atletas',
  path: '/atletas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCampoRoute = AuthenticatedCampoRouteImport.update({
  id: '/_authenticated/campo',
  path: '/campo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEvolucaoRoute = AuthenticatedEvolucaoRouteImport.update({
  id: '/_authenticated/evolucao',
  path: '/evolucao',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/_authenticated/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVideoRoute = AuthenticatedVideoRouteImport.update({
  id: '/_authenticated/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atletas': typeof AuthenticatedAtletasRoute
  '/campo': typeof AuthenticatedCampoRoute
  '/evolucao': typeof AuthenticatedEvolucaoRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/video': typeof AuthenticatedVideoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atletas': typeof AuthenticatedAtletasRoute
  '/campo': typeof AuthenticatedCampoRoute
  '/evolucao': typeof AuthenticatedEvolucaoRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/video': typeof AuthenticatedVideoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated/atletas': typeof AuthenticatedAtletasRoute
  '/_authenticated/campo': typeof AuthenticatedCampoRoute
  '/_authenticated/evolucao': typeof AuthenticatedEvolucaoRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/video': typeof AuthenticatedVideoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/atletas' | '/campo' | '/evolucao' | '/relatorios' | '/video'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/atletas' | '/campo' | '/evolucao' | '/relatorios' | '/video'
  id:
    | '__root__'
    | '/'
    | '/_authenticated/atletas'
    | '/_authenticated/campo'
    | '/_authenticated/evolucao'
    | '/_authenticated/relatorios'
    | '/_authenticated/video'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedAtletasRoute: typeof AuthenticatedAtletasRoute
  AuthenticatedCampoRoute: typeof AuthenticatedCampoRoute
  AuthenticatedEvolucaoRoute: typeof AuthenticatedEvolucaoRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedVideoRoute: typeof AuthenticatedVideoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/atletas': {
      id: '/_authenticated/atletas'
      path: '/atletas'
      fullPath: '/atletas'
      preLoaderRoute: typeof AuthenticatedAtletasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/campo': {
      id: '/_authenticated/campo'
      path: '/campo'
      fullPath: '/campo'
      preLoaderRoute: typeof AuthenticatedCampoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/evolucao': {
      id: '/_authenticated/evolucao'
      path: '/evolucao'
      fullPath: '/evolucao'
      preLoaderRoute: typeof AuthenticatedEvolucaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/video': {
      id: '/_authenticated/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof AuthenticatedVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedAtletasRoute: AuthenticatedAtletasRoute,
  AuthenticatedCampoRoute: AuthenticatedCampoRoute,
  AuthenticatedEvolucaoRoute: AuthenticatedEvolucaoRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedVideoRoute: AuthenticatedVideoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
